[package]
name = "ffmpeg-nd-sys"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = "0.72.0"

[features]
default = ["avcodec", "avformat", "aom", "x264", "openh264"]
avcodec = []
avformat = []
aom = []
x264 = []
openh264 = []
